config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    get "/custom_sign_out" => "devise/sessions#destroy", as: :custom_destroy_user_session
  end

  root 'users#index'
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create] do
      resources :comments, only: [:new, :create]
      member do
        post 'like'
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  attribute :author_id, :integer
  attribute :post_id, :integer
  attribute :text, :text

  belongs_to :post, counter_cache: true
  belongs_to :author, class_name: 'User'

  def update_post_comments_count
    post.update(comments_count: post.comments.count)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  attribute :author_id, :integer
  attribute :post_id, :integer

  belongs_to :post, counter_cache: true
  belongs_to :author, class_name: 'User'

  def update_post_likes_count
    post.update(likes_count: post.likes.count)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  attribute :author_id, :integer
  attribute :title, :string
  attribute :text, :text
  attribute :comments_count, :integer
  attribute :likes_count, :integer

  belongs_to :author, class_name: 'User', counter_cache: true
  has_many :comments
  has_many :likes

  before_validation :set_default_likes_n_comment_counts

  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_count, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_count, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  after_create :update_author_posts_count
  after_destroy :update_author_posts_count

  def set_default_likes_n_comment_counts
    self.comments_count ||= 0
    self.likes_count ||= 0
  end

  def update_author_posts_count
    author.update(posts_count: author.posts.count)
  end

  def recent_comments
    comments.order(created_at: :desc).limit(5)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable, :confirmable
  attribute :name, :string
  attribute :bio, :text
  attribute :photo, :string
  attribute :posts_count, :integer

  has_many :posts, foreign_key: :author_id
  has_many :comments, foreign_key: :author_id
  has_many :like, foreign_key: :author_id

  before_create :set_default_photo
  before_validation :set_default_posts_count
  validates :name, presence: true
  validates :posts_count, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def set_default_posts_count
    self.posts_count ||= 0
  end

  def set_default_photo
    self.photo ||= "https://randomuser.me/api/portraits/men/#{rand(1..100)}.jpg"
  end

  def recent_posts
    posts.order(created_at: :desc).limit(3)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def add_like
    @like = Like.new(user: @user, post: @post)
    nil unless @like.save
  end

  helper_method :current_user

  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_user_post

  def new
    @comment = @post.comments.build
  end

  def create
    @comment = @post.comments.new(comment_params)
    @comment.author = current_user
    if @comment.save
      redirect_to user_post_path(@user, @post), notice: 'Comment was successfully created.'
    else
      render 'new'
    end
  end

  def comment_params
    params.require(:comment).permit(:text)
  end

  def set_user_post
    @user = User.find(params[:user_id])
    @post = @user.posts.find(params[:post_id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]
  # before_action :set_user

  def index
    @page_title = 'Post Index Page'
    @user = User.find(params[:user_id])
    @posts = @user.posts
  end

  def show
    @page_title = 'Post Show Page'
    @user = User.find(params[:user_id])
    @post = Post.find(params[:id])
  end

  def new
    @post = current_user.posts.build
    @user = current_user
  end

  def create
    @post = current_user.posts.new(post_params)
    if @post.save
      redirect_to user_post_path(current_user, @post), notice: 'Post was successfully created.'
    else
      render :new
    end
  end

  def like
    @user = User.find(params[:user_id])
    @post = @user.posts.find(params[:id])
    @like = @post.likes.create(author: current_user)
    @like.save
    redirect_to user_post_path(@user, @post)
  end

  def post_params
    params.require(:post).permit(:title, :text)
  end

  def set_user
    @user = User.find(params[:user_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]

  def index
    @page_title = 'User Index Page'
    @users = User.all
  end

  def show
    @page_title = 'User Show Page'
    @user = User.find(params[:id])
    @posts = @user.posts
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/new.html.erb
<a href="<%= user_post_path(@user, @post) %>">
  <button id="back-btn">⬅ Back</button>
</a>
<h1 id = "form-title">Create a New Comment</h1>
<%= form_with(model: [@post, @comment], url: user_post_comments_path(@user, @post)) do |form| %>
  <div class = "form-container">
    <div class="field">
      <%= form.label :text %>
      <%= form.text_area :text %>
    </div>

    <div class="actions">
      <%= form.submit 'Create Comment' %>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @page_title %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <div class = log-container>
    <% if user_signed_in? %>
      <%= link_to "Profile", edit_user_registration_path %>
      <%= link_to "Log out", custom_destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to "Login", new_user_session_path %>
      <%= link_to "Sign Up", new_user_registration_path %>
    <% end %>
    </div>

    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<%= render "shared/user_box", user: @user %>

<%# I'm sure that I solved N+1 problem when fetching all posts and their comments for a user, I'm using @posts.includes comments: :author) instead of @posts in my controllers %>
<% @posts.includes(comments: :author).each do |post| %>
  <a class = "post-box" href="<%= user_post_path(@user, post) %>">
    <div class = "bio-box-container">
      <%= render "shared/post_box", post: post, user: @user%>
    </div>
      <%= render "shared/comment_box", comments: post.comments.last(5) %>
  </div>
<% end %>

<% if current_user == @user %>
<a class = "btn-container" href="<%= new_user_post_path(@user) %>">
    <button class='new-post-btn'>Create a new post</button>
</a>
<% end %>

<a class = "btn-container" href="<%= user_path(@user) %>">
  <button class = "back">⬅ Back</button>
</a>

app/views/posts/new.html.erb
<a href="<%= user_path(@user) %>">
  <button id="back-btn">⬅ Back</button>
</a>
<h1 id = "form-title">Create a New Post</h1>
<%= form_with(model: [@user, @post], url: user_posts_path(@user)) do |form| %>
  <div class = "form-container">
    <div class="field">
      <%= form.label :title %>
      <%= form.text_field :title %>
    </div>

    <div class="field">
      <%= form.label :text %>
      <%= form.text_area :text %>
    </div>

    <div class="actions">
      <%= form.submit 'Create Post' %>
    </div>
  </div>
<% end %>

app/views/posts/show.html.erb
<div class= "post-container">
  <div class = "post">
    <div class = "post-header">
      <p>Post #<%= @post.id%> by <%= @user.name%></p>
      <div class = "likes-corner">
        <p>Comments: <%= @post.comments_count %>, Likes: <%= @post.likes_count %></p>
          <%= button_to "Like", like_user_post_path(@user, @post), method: :post %>
      </div>
    </div>
    <p class = "post-text">
    <br>
    <%= @post.text%>
    </p>
  </div>

</div>
<%= render "shared/comment_box", comments: @post.recent_comments %>

<a class = "btn-container" href="<%= new_user_post_comment_path(@user, @post) %>">
    <button class='new-comment-btn'>Create a new comment</button>
</a>

<a class = "btn-container" href="<%= user_posts_path(@user) %>">
  <button class = "see-all-posts">⬅ Back</button>
</a>

<a class = "btn-container" href="<%= url_for(action: 'index', controller: 'users') %>">
  <button class = "back">Home</button>
</a>

app/views/shared/_comment_box.html.erb
<div class = "comments-box-container">
  <div class = "comments-box">
    <% comments.each do |comment| %>
      <p class = "comment-box"><%= comment.author.name %>: <%= comment.text %></p>
    <% end %>
  </div>
</div>

app/views/shared/_post_box.html.erb
<div class = "bio-box">
  <p><%= post.title %></p>
  <br>
  <p><%=  post.text.truncate_words(25) %>...</p>
  <p class = "counters">Comments: <%= post.comments_count %>, Likes: <%= post.likes_count %></p>
</div>

app/views/shared/_user_box.html.erb
<a class = "user-box" href="<%= user_path(user) %>">
  <div class = "img-container">
    <img class = "user-image" src= "<%= user.photo %>" alt="<%= user.name %>_image">
  </div>
  <div class = "user-info-box">
    <p class = "user-name"><%= user.name %></p>
    <p class = "number-of-posts">Number of posts: <%= user.posts_count %></p>
  </div>
</a>

app/views/users/index.html.erb
<ul id="users">
  <% @users.each do |user| %>
    <%= render "shared/user_box", user: user %>
  <% end %>
</ul>

app/views/users/show.html.erb
<%= render "shared/user_box", user: @user %>
<div class = "bio-box-container">
  <div class = "bio-box">
    <p>Bio</p>
    <br>
    <p><%=@user.bio%></p>
  </div>
</div>
<% @user.recent_posts.each do |post| %>
  <a class = "bio-box-container" href="<%= user_post_path(@user, post) %>">
    <%= render "shared/post_box", post: post %>
  </a>
<% end %>
<a class = "btn-container" href="<%= user_posts_path(@user) %>">
  <button class = "see-all-posts">See all posts</button>
</a>

<% if current_user == @user %>
<a class = "btn-container" href="<%= new_user_post_path(current_user) %>">
    <button class='new-post-btn'>Create a new post</button>
</a>
<% end %>

<a class = "btn-container" href="<%= users_path %>">
  <button class = "back">⬅ Back</button>
</a>